### ISSUE TITLE
web.whatsapp.com not working

### ISSUE THREAD

**Issue by sanjaykumarm** [delight-im/Android-AdvancedWebView#121] opened 2017-03-10 12:56 UTC
web.whatsapp.com is not working when you load the url second time. It redirects to whatsapp.com when you load the url.

**Comment by ocram** [comment] 2017-03-11 22:08
1. Is your version of this library up-to-date?
 1. Can you verify this on a real device, as opposed to an emulator?
 1. Is [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) up-to-date on your device?
 1. Can you check whether calling

    ```java
    mWebView.setDesktopMode(true);
    ```

    before loading the URL makes any difference?

 1. As a last resort, could you replace this library with Android's plain `WebView` again, temporarily, to see if that makes any difference?

Thanks!

**Comment by sanjaykumarm** [comment] 2017-03-12 17:01
1.  Is your version of this library up-to-date
- Yes, its upto date. I already used latest version from git. Run the same demo by replacing url.

  2.  Can you verify this on a real device, as opposed to an emulator?
- Yes, tested in real device. In Samsung tab 5.0 OS and moto g play 6.0 OS

  3.  Is Android System WebView<https://play.google.com/store/apps/details?id=com.google.android.webview> up-to-date on your device?
- Yes

  4.  Can you check whether calling

mWebView.setDesktopMode(true);
- Trying the same by requesting desktop mode true.

before loading the URL makes any difference?

  5.  As a last resort, could you replace this library with Android's plain WebView again, temporarily, to see if that makes any difference?
- Loads first time correct then again redirects to whats app official site. The same thing is happening with your lib as well.

________________________________________

**Comment by ocram** [comment] 2017-03-13 23:21
The user-agent string is definitely the reason for the redirect here, I'd say. I don't know why

```java
mWebView.setDesktopMode(true);
```

doesn't work, but it probably does not look similar enough to desktop browsers, in WhatsApp's terms.

Please try setting another user-agent string manually, e.g.

```java
mWebView.getSettings().setUserAgentString("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:52.0) Gecko/20100101 Firefox/52.0");
```

Does that work?

**Comment by sanjaykumarm** [comment] 2017-03-14 05:07
Same result using your user agent string. First time it loads correctly, but from second time on wards, it creates issue and redirects to its official site. So I think in first load, they are storing some data. I also disable the cookies but it didn't help me.


I wondered that how this app https://play.google.com/store/apps/details?id=com.whatscan? make it possible ? It is working fine.


________________________________

**Comment by ocram** [comment] 2017-03-14 19:48
Sorry to hear that it's still not working. Don't know what that other app is doing to make it work. WhatsApp must be doing some checks to find out if you're on a phone or tablet/desktop. Hope you'll find out what it is.

But this is hardly a bug in WebView, and since Android's built-in WebView shows the same behavior, *verifiably* not a bug in this library here. So the only thing we can do is close this issue. Sorry!

**Closed by ocram** 2017-03-14 19:48 UTC
Labels: question

**Comment by Bhuvan-Arora** [comment] 2017-06-20 08:26
Try this User agent @sanjaykumarm 

**_mWebView.getSettings().setUserAgentString("Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:52.0) Gecko/20100101 Firefox/52.0");_**

This User agent is working.
I recently tried and successfully load http://web.whatsapp.com in android webView with above mention User Agent

**Comment by sanjaykumarm** [comment] 2017-06-20 09:02
@Bhuvan-Arora This will work on first time start up of the app. From next start up, it goes to official site. Again when you do clear data and load the app, it works but again when you open the app second time then it fails to load the desired web page (i.e. qr code page).

**Comment by Bhuvan-Arora** [comment] 2017-06-20 10:00
@sanjaykumarm  Then you have to try windows-7 User Agent. I think it shall work. 
Otherwise Notify me again, then I will check the code and try to find out the solution in my vacant schedule. 
Thanks

**Comment by sanjaykumarm** [comment] 2017-06-20 11:36
@Bhuvan-Arora I tried everything but didnt work for me. In your case is it working every time ? And if you logged in by scanning code then is it maintained until you signed out ?

**Comment by Bhuvan-Arora** [comment] 2017-06-20 20:00
@sanjaykumarm During R&D of your issue I successfully find the relevant solution and finally uploaded the build apk on Google Play. You can test it here.
https://play.google.com/store/apps/details?id=coders.phoenix.whatscan

And if it is working according to your requirement then please Don't forget to give your valuable feedback on playstore.

Send me your email id. I will mail the working user agent there.

**Comment by vrgomes** [comment] 2017-07-21 13:10
Hi everyone,
I'm having the same issue. Even forcing a desktop browser user-agent the WhatsApp don't open the Webview in Desktop mode but on some random website.
Does anyone have a fix for this?

Greetings.

**Comment by AfreenR** [comment] 2017-08-10 12:25
@Bhuvan-Arora  plz tell me for that issue which user agent have you used ??

**Comment by ocram** [comment] 2017-08-10 15:16
It should be pretty easy to test if this really depends on the user-agent string:

First, open Firefox or Chrome on your desktop machine where the unwanted redirect (upon refresh) for `web.whatsapp.com` does *not* happen. Copy that browser's user-agent string and use it in your Android application. Now, if the unwanted redirect does not occur anymore with that new user-agent string on Android, you're done. If it still happens, that problem does not (only) depend on the user-agent string.

Instead, it might also be feature detection and the redirect might then occur upon discovering missing features. WhatsApp may require the following features, among others:

 * `window.localStorage`
 * `window.sessionStorage`
 * `window.URL`
 * `window.crypto && window.crypto.getRandomValues`
 * `window.WebSocket`
 * `window.crypto && (window.crypto.subtle || window.crypto.webkitSubtle)`
 * `window.Worker`

**Comment by vrgomes** [comment] 2017-08-20 15:05
Hi, I'm using this user-agent:
webSettings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36");

And I'm having the behavior that sanjaykumarm is reporting.

**Comment by sgrassman** [comment] 2017-09-10 14:49
Same Issue, It only works once but once I reopen the app i got the redirect :/ Can you share your solution @Bhuvan-Arora

**Comment by vrgomes** [comment] 2017-10-07 16:24
Anyone knows how to fix this?

Greetings.

**Comment by ocram** [comment] 2017-10-09 20:41
@vrgomes and @serezin See the [comment above](https://github.com/delight-im/Android-AdvancedWebView/issues/121#issuecomment-321582531) for details about the most likely cause for this issue.

**Comment by vrgomes** [comment] 2017-10-09 20:52
@ocram 
that's impossible because on the first run it works perfectly. The next runs fail.
Also if I clear data + cache it works good again. 

Greetings.

**Comment by ocram** [comment] 2017-10-09 21:08
@vrgomes But it cannot be the user-agent (alone), either, because we have excluded that with various tests, right? If you feel that it's your cookies, stored data and cache, you should inspect what's in there and affects the second page load.

**Comment by statickidz** [comment] 2017-10-12 10:39
I'm trying to make this work also

**Comment by statickidz** [comment] 2017-10-14 15:18
I finally make this work with mWebView.setDesktopMode(true) but there is a problem with the buttons in the chats, seems not to be clickable and some images are not loading

**Comment by ocram** [comment] 2017-10-16 20:35
@statickidz It’s unlikely that `mWebView.setDesktopMode(true)` alone did the trick, isn’t it? I’m sure others have tried that as well. For any problems with buttons or images, we’d probably need screenshots to see what the issue may be.

**Comment by statickidz** [comment] 2017-10-17 15:29
Yes, it did the trick and also did in the normal WebView component implementing the same code in the user-agent. Here is some examples you can help to dive in this.

I also tried with [crosswalk webview](https://github.com/dougdiego/CrosswalkDemo) and it runs smootly at least in emulators buttons for submenus are actually working also in crosswalk.

Submenus not clickables, main manu catch the click as you can see
![](https://i.gyazo.com/4c6158458d9749ca21dfe6669da2bee0.gif)

Another example
![](https://i.gyazo.com/60a14deaf00bda0693f0c3397d3f0f7d.gif)

Not loading images example, only GIFs, I think blob data can be the issue
![](https://i.gyazo.com/ffa7c217ef0afea8b41c0700cdc0c5b6.gif)

**Comment by vrgomes** [comment] 2017-12-05 22:42
The mWebView.setDesktopMode(true) does not work. After a refresh it loses the desktop mode. Or simply exiting and entering again also happens.
Only by making a full data + cache clear is the only way for it to work again.

I really don't understand how this is possible. Has anyone overcome this?

**Comment by ocram** [comment] 2017-12-09 00:31
@vrgomes See https://github.com/delight-im/Android-AdvancedWebView/issues/121#issuecomment-321582531 for the most likely explanation so far. You can check this yourself and see if that’s really the reason or not. Just check the existence of these features via JavaScript.

**Comment by ArunVicky001** [comment] 2017-12-28 18:54
In my case i tried custom user agent , viewport , display size ,Advanced WebView, mWebView.setDesktopMode(true) nothing is worked for me..

The thing is its working good in android emulator not in real device. 
In fact it loads the correct QRcode screen first time in real android mobile, if the activity loads the web view again it always redirect the https://www.whatsapp.com rather then https://web.whatsapp.com

I described my problem here: 
https://stackoverflow.com/questions/47946658/android-webview-desktop-website-wont-work?noredirect=1#comment82880069_47946658

If anyone have the solution please help me how to solve this

**Comment by ArunVicky001** [comment] 2017-12-28 18:58
@Bhuvan-Arora Am wondering about u, Could you please tell me what i missing in my code  https://stackoverflow.com/questions/47946658/android-webview-desktop-website-wont-work?noredirect=1#comment82880069_47946658

**Comment by ArunVicky001** [comment] 2017-12-28 19:02
@sanjaykumarm Hi did you fix the issue?

**Comment by sanjaykumarm** [comment] 2017-12-29 04:13
@ArunVicky001 AS statickidz mention above, I used crosswalk webview to resolve the issue. I tried all possible combination of user agent in 'Android-AdvancedWebView', but it was not working in all the devices. But crosswalk webview is working fine - only disadvantage is that it increase apk size too much but there is no any alternate solution. Hope it helps.

**Comment by ArunVicky001** [comment] 2017-12-29 05:49
@sanjaykumarm Thankyou very much for your reply. I'll do with crosswalk webview,  Does @Bhuvan-Arora   tell any suggestion regarding this.

**Comment by sanjaykumarm** [comment] 2017-12-29 05:56
@ArunVicky001 WC 👍 Happy to help you

**Comment by vrgomes** [comment] 2017-12-29 09:59
Hi, so by using crosswalk webview it means that we have to remove the Android-AdvancedWebView?
Does anyone have a tutorial for the crosswalk webview?

Greetings.

**Comment by highwaycrossingfrog** [comment] 2018-03-27 22:06
If anyone is still interested in a fix, I got it to work by sideloading Firefox and forcing it to use desktop mode via the instructions on this thread https://support.mozilla.org/en-US/questions/1114055
NB there doesn't seem to be an add on that will do the trick any more, you have to edit the about:config

**Comment by highwaycrossingfrog** [comment] 2018-03-27 22:15
So basically what everyone said about the user agent, but using this one on Firefox: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by highwaycrossingfrog** [comment] 2018-03-27 22:19
On a Kindle Fire HD 10 7th gen

**Comment by ArunVicky001** [comment] 2018-05-29 10:09
@highwaycrossingfrog If anyone is still interested in a fix, I got it to work by sideloading Firefox and forcing it to use desktop mode via the instructions on this thread https://support.mozilla.org/en-US/questions/1114055
NB there doesn't seem to be an add on that will do the trick any more, you have to edit the about:config


Could you please explain me how did you achieve this, 
i wanted to request the desktop site in android WebView  not in firefox. Is there is any possibilities to achieve that?

Thanks in advance.

**Comment by ArunVicky001** [comment] 2018-05-29 10:11
@Bhuvan-Arora Please give any idea to do this ?

**Comment by Bhuvan-Arora** [comment] 2018-05-29 12:58
**Solution**  
Use below user agent for whatsapp web. It will definitely work.

Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36

Or you can also search it on web ""latest user agent of google chrome for window-7"".

**Warning** : But please don't try to upload it on Google Play, It is not legal according to google play policies and it may cause suspension of your google play account.

**Comment by ArunVicky001** [comment] 2018-05-29 15:46
@Bhuvan-Arora Thank you very much for your reply but the above user agent only works at first time 

I used the below code, Please check whether its i made any mistake in the code  



```
public   void  loadView(){
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setLoadWithOverviewMode(true);
        webView.getSettings().setUseWideViewPort(true);
        webView.getSettings().setSupportZoom(false);
        webView.getSettings().setBuiltInZoomControls(false);
        webView.getSettings().setDisplayZoomControls(false);
        webView.setScrollBarStyle(WebView.SCROLLBARS_OUTSIDE_OVERLAY);
        webView.getSettings().setDomStorageEnabled(true);
        webView.setWebChromeClient(new WebChromeClient());
        String ua = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36";
        webView.getSettings().setUserAgentString(ua);
        Log.v("WebView","On create");
        webView.setWebViewClient(new WebViewClient()
        {
            @Override
            public void onPageStarted(WebView view, String url, Bitmap favicon) {
                super.onPageStarted(view, url, favicon);
                Log.d("WebView", "onPageStarted.." + url);
            }

            @Override
            public void onPageFinished(WebView view, String url) {
                Log.d("WebView", "onPageStarted.." + url);
                super.onPageFinished(view, url);
            }

            @Override
            public void onLoadResource(WebView view, String url) {
                // TODO Auto-generated method stub
                Log.d("WebView", "onLoadResource.." + url);
                super.onLoadResource(view, url);
            }
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                System.out.println("shouldOverrideUrlLoading :-" + url);
                return super.shouldOverrideUrlLoading(view, url);
            }
        });
            webView.loadUrl(currentUrl);
    }
```

**Comment by ArunVicky001** [comment] 2018-05-30 10:48
@Bhuvan-Arora  Could you please check my code and suggest me to do in right way

**Comment by rashmi2213** [comment] 2019-02-28 21:40
> @sanjaykumarm During R&D of your issue I successfully find the relevant solution and finally uploaded the build apk on Google Play. You can test it here.
> https://play.google.com/store/apps/details?id=coders.phoenix.whatscan
> 
> And if it is working according to your requirement then please Don't forget to give your valuable feedback on playstore.
> 
> Send me your email id. I will mail the working user agent there.

Hello, Can you please send me solution to rashmi.karma2213@gmail.com ?

**Comment by abeeriqbal** [comment] 2019-06-08 17:08
settings.setDomStorageEnabled(true);
webView?.settings?.userAgentString = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
This is working for web.whatsapp and Web.wechat,

**Comment by sureapps** [comment] 2020-07-29 10:36
> setDomStorageEnabled
this user agent not work

![image](https://user-images.githubusercontent.com/22068401/88790178-64e16400-d1b5-11ea-80fd-4525742ccc10.png)

**Comment by sureapps** [comment] 2020-07-29 10:36
> settings.setDomStorageEnabled(true);
> webView?.settings?.userAgentString = "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
> This is working for web.whatsapp and Web.wechat,


this is not work 

![image](https://user-images.githubusercontent.com/22068401/88790243-7b87bb00-d1b5-11ea-9022-d8f303b8782b.png)

**Comment by AnkitaManiya** [comment] 2021-06-19 05:21
I recently tried and successfully load http://web.whatsapp.com in android webView with below mention functinality:--


private void setWebView()
 {
                webView = (WebView) findViewById(R.id.webViews);
                webView.getSettings().setJavaScriptEnabled(true);
                webView.getSettings().setDomStorageEnabled(true);
                webView.getSettings().setBuiltInZoomControls(true);
                webView.getSettings().setDisplayZoomControls(false);
                webView.getSettings().setUserAgentString("Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.4) Gecko/20100101 
                Firefox/44.0");
                webView.getSettings().setMediaPlaybackRequiresUserGesture(false);
                webView.getSettings().setJavaScriptEnabled(true);
                webView.setWebViewClient(new MyWebViewClient());
                webView.getSettings().setSaveFormData(true);
                webView.getSettings().setLoadsImagesAutomatically(true);
                webView.getSettings().setUseWideViewPort(true);
                webView.getSettings().setAllowFileAccessFromFileURLs(true);
                webView.getSettings().setBlockNetworkImage(false);
                webView.getSettings().setBlockNetworkLoads(false);
                webView.getSettings().setLayoutAlgorithm(WebSettings.LayoutAlgorithm.NORMAL);
                webView.getSettings().setSupportMultipleWindows(true);
                webView.getSettings().setJavaScriptCanOpenWindowsAutomatically(true);
                webView.getSettings().setLoadWithOverviewMode(true);
                webView.getSettings().setNeedInitialFocus(false);
                webView.getSettings().setAppCacheEnabled(true);
                webView.getSettings().setDatabaseEnabled(true);
                webView.getSettings().setDomStorageEnabled(true);
                webView.getSettings().setGeolocationEnabled(true);
                webView.getSettings().setCacheMode(2);
                webView.setScrollBarStyle(0);
                webView.getSettings().setUserAgentString("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 
                (KHTML, like Gecko) Chrome/78.0.3904.96 Safari/537.36");
                final StringBuilder sb = new StringBuilder();
                sb.append("https://web.whatsapp.com/🌐/");
                sb.append(Locale.getDefault().getLanguage());
                webView.loadUrl(sb.toString());

    }


private class MyWebViewClient extends WebViewClient {
        @Override
        public void onPageFinished(WebView webView, String str) {
            loadingView.setVisibility(View.GONE);
        }
        @Override
        public void onPageStarted(WebView webView, String str, Bitmap bitmap) {}

        private MyWebViewClient() {
        }

        @Override
        public boolean shouldOverrideUrlLoading(WebView webView, String str) {
            loadingView.setVisibility(View.VISIBLE);
            String str2 = "WhtasWeb";
            Log.e(str2, "shouldOverrideUrlLoading: " + str);
            if (Uri.parse(str).getHost().contains(".whatsapp.com")) {
                return true;
            }
           getActivity().startActivity(new Intent("android.intent.action.VIEW", Uri.parse(str)));
            return true;
        }
    }

**Comment by ArunVicky001** [comment] 2021-06-19 05:36
@AnkitaManiya Thanks for sharing your answers hope this will help us

**Comment by sanjaykumarm** [comment] 2021-06-21 02:57
@AnkitaManiya Can you please share your email ? Wanted little more help, so that I can contact you there. Wanted to help more developers if they can also get more benefits of problems they are facing.

**Comment by i-nasser** [comment] 2022-09-28 01:12
Try this settings

```
webViewWorker = findViewById(R.id.webViewWorker);
webViewWorker.getSettings().setJavaScriptEnabled(true);
webViewWorker.getSettings().setLoadsImagesAutomatically(true);
webViewWorker.getSettings().setLoadWithOverviewMode(true);
webViewWorker.getSettings().setUseWideViewPort(true);
webViewWorker.getSettings().setDomStorageEnabled(true);
webViewWorker.getSettings().setBuiltInZoomControls(true);
String userAgent = webViewWorker.getSettings().getUserAgentString();
try {
    String androidString = webViewWorker.getSettings().getUserAgentString().substring(userAgent.indexOf("("),userAgent.indexOf(")") + 1);
    userAgent = webViewWorker.getSettings().getUserAgentString().replace(androidString,"X11; Linux x86_64");
} catch (Exception e) {
    e.printStackTrace();
}

webViewWorker.getSettings().setUserAgentString(userAgent);
webViewWorker.loadUrl("https://web.whatsapp.com");
```
