### ISSUE TITLE
Custom headers not sent with every request

### ISSUE THREAD

**Issue by oderayi** [delight-im/Android-AdvancedWebView#27] opened 2015-10-14 12:07 UTC
How do you manipulate request URL before it is sent?
My guess is that I need to do override a method in the WebViewClient but I have no way of doing that since you do not expose the WebViewClient.

Is there a workaround?

Thanks

EDIT: Found "setWebViewClient" method.

**Comment by mwaclawek** [comment] 2015-10-14 13:51
Thanks for your question and posting the solution :)

Yes, the normal `setWebViewClient(...)` from the `WebView` class can be used.

There was some effort to extend the `WebView` class but at the same time keep all the behaviour and available methods the same. So you should be able to use all things that a normal `WebView` exposes.

**Comment by oderayi** [comment] 2015-10-14 13:56
Thank you very much!

I had to do this:

webView.setWebViewClient(new WebViewClient(){

            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                view.loadUrl(url, getExtraHeaders());
                return true;

            }
        });

to get my custom headers to show up at my backend.
Normally I would have used the "webView.addHttpHeader" method, but for reason, I did't set the custom headers at my backend.

You might need to look at it.

Thanks again!

**Comment by mwaclawek** [comment] 2015-10-14 14:01
This looks perfectly fine and is a clever solution!

Indeed, the values from `addHttpHeader(...)` are only used when calling `loadUrl(...)`, i.e. for your initial request. Do you feel that this should be changed?

**Comment by oderayi** [comment] 2015-10-14 14:06
I think the design of `addHttpHeader` is pretty good because I don't have to implement a `WebViewClient` callback to add custom headers.

My point is: I used it at first, but it seem not to work so I went the custom `WebViewClient` way.

Calling `addHttpHeader` is pretty more convenient but it seem not to be working.

**Comment by mwaclawek** [comment] 2015-10-15 06:33
Yes, the issue is that the values from `addHttpHeader(...)` are only used when you call `loadUrl(...)`.

This is typically your first request -- where you set the page from code.

Whenever the user follows a link or redirect then, `loadUrl(...)` will not be called. You see?

So maybe we should incorporate your fix with `shouldOverrideUrlLoading(...)` into this library. It seems that will help.

Setting the headers there seems to work *every time*. But we have to check against side effects and unexpected problems this could cause, of course.

**Comment by oderayi** [comment] 2015-10-15 10:51
Yeah, very good. I think it will also be nice to have a switch to enable or disable the sending of the headers on every request just in case it is not desirable in some other scenarios (overheads and what not). 

In my scenario, I want to have the headers sent with every request to different the requests by device and version at my backend.

Thank you.

**Comment by mwaclawek** [comment] 2015-10-18 22:04
Great, we'll leave this issue open and implement a fix as soon as possible :)

Probably, we don't even need a switch, because looking at the method names and documentation, it really is a bug. So the behaviour that you requested should really be what *everyone* actually wanted in *every* use case.

Otherwise, one may call `removeHttpHeader(...)` after the initial request to remove the headers again.

**Comment by scheccia1** [comment] 2016-03-19 23:57
Hi, I have the same problem.
I imported it in android studio, but don't recognize any function... i have a folder in my project called Android-AdvancedWebView and 3 file:
Android-AdvancedWebView.iml
Android-AdvancedWebView.jar
build.gradle

**Comment by mwaclawek** [comment] 2016-03-20 19:58
@scheccia1 Thanks, but doesn't really look like you have the same problem described in this thread. Your problem is that you simply can't get the library working, right? Can you try copying the `AdvancedWebView.java` source file to a package `im.delight.android.webview` in your own source code instead?

**Comment by scheccia1** [comment] 2016-03-21 07:59
Excuse me,I thought I had answered to other iussue where there was a logcat, and you suggested to install jar.

**Comment by mwaclawek** [comment] 2016-03-21 09:35
@scheccia1 No problem! So what about copying the source code instead of including the JAR? Does it work?

**Comment by mwaclawek** [comment] 2016-03-30 13:07
@oderayi and everyone interested: This issue has been resolved now: The fix is in https://github.com/delight-im/Android-AdvancedWebView/commit/e90fc8243ca68a23088eb4f12dd53317873d4c4c and can be used by updating your dependency (see README). Sorry for the long delay!

@scheccia1 You can include this library via Gradle now (instead of JAR).

**Closed by mwaclawek** 2016-03-30 13:07 UTC
Labels: bug
